const enc=new TextEncoder();const hash=async v=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(v)))).map(x=>x.toString(16).padStart(2,'0')).join('');const token=()=>Array.from(crypto.getRandomValues(new Uint8Array(32))).map(x=>x.toString(16).padStart(2,'0')).join('');
const json=(v,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const html=(body,status=200)=>new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Nibra — your life, in context</title><style>*{box-sizing:border-box}body{margin:0;background:#191919;color:#eee;font:16px -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;line-height:1.65}main{width:min(680px,calc(100% - 40px));margin:12vh auto}nav{display:flex;justify-content:space-between;border-bottom:1px solid #383838;padding-bottom:20px;margin-bottom:60px}a{color:inherit}h1{font-weight:500;font-size:48px;letter-spacing:-.04em;line-height:1.1}h2{font-weight:500}p{color:#b6b6b6}button,.button{display:inline-block;padding:12px 22px;background:#eee;color:#191919;border:0;border-radius:8px;font:inherit;text-decoration:none;cursor:pointer}input{padding:14px;background:#252525;border:1px solid #666;border-radius:7px;color:#fff;font:inherit;width:100%;margin:10px 0 20px}small{font-size:13px;color:#aaa}section{border-top:1px solid #333;padding:25px 0}.wordmark{font-weight:650;letter-spacing:.12em}.secondary{background:#303030;color:#eee;margin:10px}code{color:#eee;background:#303030;padding:4px 10px}</style></head><body><main><nav><a class="wordmark" href="/">NIBRA</a><a href="/account">Your account ↗</a></nav>${body}</main></body></html>`,{status,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'",'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'}});
function identity(req){const id=req.headers.get('oai-authenticated-user-id'),email=req.headers.get('oai-authenticated-user-email');let name=req.headers.get('oai-authenticated-user-full-name')||'';if(req.headers.get('oai-authenticated-user-full-name-encoding')==='percent-encoded-utf-8')try{name=decodeURIComponent(name)}catch{name=''}return id&&email?{id,email,name:name||email.split('@')[0]}:null}
const signin=path=>Response.redirect('/signin-with-chatgpt?return_to='+encodeURIComponent(path),302);
export default {async fetch(req,env){try{const u=new URL(req.url),db=env.DB||env.DATABASE;const user=identity(req);const signIn=path=>Response.redirect(u.origin+'/signin-with-chatgpt?return_to='+encodeURIComponent(path),302);
if(u.pathname==='/health')return json({ok:true,service:'Nibra accounts',version:'1.1.0'});
if(u.pathname==='/')return Response.redirect('https://github.com/Aghosh-mv/nibra-betterlife/releases',302);
if(u.pathname==='/privacy')return html('<h1>Your data stays yours.</h1><p>Account authentication uses Sign in with ChatGPT. Our account service stores your account identifier, display email/name, expiring device authorization codes, and revocable session hashes. Workspace records and model credentials remain on the desktop device.</p><p>When you ask your own AI provider a question, Nibra sends the conversation and only the context you enable. Providers process this data under their own terms. Private memories are excluded.</p><p>Delete local workspace data inside Privacy Center. Signing out revokes the current desktop session. Device authorization expires after ten minutes; account sessions expire after thirty days. Expired authentication records are cleaned up during service activity.</p><a class="button" href="/account">Manage account</a>');
if(u.pathname==='/downloads')return Response.redirect(env.RELEASE_URL||'https://github.com/Aghosh-mv/nibra-betterlife/releases',302);
if(u.pathname==='/account'){if(!user)return html('<h1>A space that is only yours.</h1><p>Sign in securely with ChatGPT, or create a ChatGPT account during sign-in. Nibra never receives your password.</p><a class="button" href="/signin-with-chatgpt?return_to=%2Faccount" target="_top">Continue with ChatGPT</a>');return html(`<h1>Hello, ${esc(user.name)}.</h1><p>Signed in as ${esc(user.email)}.</p><p>Open Nibra on your computer and choose Sign in to connect that device. Each account has its own workspace.</p><a class="button" href="/signout-with-chatgpt?return_to=%2Faccount" target="_top">Sign out</a>`)}
if(!db)return json({error:'Account storage is not configured.'},503);
const now=Date.now();if(Number(req.headers.get('Content-Length')||0)>8192)return json({error:'Request is too large.'},413);
if(u.pathname==='/api/device/start'&&req.method==='POST'){const total=await db.prepare('SELECT COUNT(*) AS n FROM device_codes WHERE expires > ?').bind(now).first();if(total.n>5000)return json({error:'Too many sign-in requests. Try again shortly.'},429);const code=token(),short=Array.from(crypto.getRandomValues(new Uint8Array(5))).map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase();await db.batch([db.prepare('DELETE FROM device_codes WHERE expires < ?').bind(now),db.prepare('DELETE FROM sessions WHERE expires < ?').bind(now),db.prepare('INSERT INTO device_codes (hash, code, expires, consumed) VALUES (?, ?, ?, 0)').bind(await hash(code),short,now+600000)]);return json({deviceCode:code,userCode:short,verificationUrl:u.origin+'/device?code='+short,expiresAt:now+600000})}
if(u.pathname==='/device'){if(!user)return signIn(u.pathname+u.search);const code=(u.searchParams.get('code')||'').toUpperCase();const record=await db.prepare('SELECT code, expires, user_id, consumed FROM device_codes WHERE code = ?').bind(code).first();if(!record||record.expires<now||record.consumed)return html('<h1>This request has expired.</h1><p>Start sign-in again from the desktop app.</p>',400);return html(`<h1>Connect your desktop?</h1><p>Confirm that Nibra on your computer shows this exact code:</p><h2><code>${esc(code)}</code></h2><p>You are authorizing the desktop as <strong>${esc(user.email)}</strong>. Only approve a sign-in you started yourself.</p><form action="/api/device/approve" method="POST"><input type="hidden" name="code" value="${esc(code)}"><button>Connect this device</button></form>`)}
if(u.pathname==='/api/device/approve'&&req.method==='POST'){if(!user)return json({error:'Sign in required.'},401);if(req.headers.get('Origin')!==u.origin)return json({error:'Invalid request origin.'},403);const code=String((await req.formData()).get('code')||'');const result=await db.prepare('UPDATE device_codes SET user_id = ?, email = ?, name = ? WHERE code = ? AND expires > ? AND user_id IS NULL AND consumed = 0').bind(user.id,user.email,user.name,code,now).run();if(!result.meta.changes)return html('<h1>This code is no longer available.</h1><p>Start again in the desktop app.</p>',400);return html('<h1>You’re connected.</h1><p>Return to Nibra on your computer. You can close this window.</p>')}
if(u.pathname==='/api/device/poll'&&req.method==='POST'){const {deviceCode}=await req.json();if(typeof deviceCode!=='string'||deviceCode.length!==64)return json({error:'Invalid code.'},400);const h=await hash(deviceCode);const record=await db.prepare('SELECT * FROM device_codes WHERE hash = ?').bind(h).first();if(!record||record.expires<now||record.consumed)return json({error:'Sign-in expired. Start again.'},410);if(!record.user_id)return json({pending:true});const result=await db.prepare('UPDATE device_codes SET consumed = 1 WHERE hash = ? AND consumed = 0').bind(h).run();if(!result.meta.changes)return json({error:'Code already used.'},410);const accessToken=token(),expiresAt=now+30*86400000;await db.prepare('INSERT INTO sessions (hash, user_id, email, name, expires) VALUES (?, ?, ?, ?, ?)').bind(await hash(accessToken),record.user_id,record.email,record.name,expiresAt).run();return json({accessToken,expiresAt,user:{id:record.user_id,email:record.email,name:record.name}})}
if(u.pathname==='/api/session'){const bearer=req.headers.get('Authorization')||'';if(!bearer.startsWith('Bearer '))return json({error:'Sign in required.'},401);const h=await hash(bearer.slice(7));if(req.method==='DELETE'){await db.prepare('DELETE FROM sessions WHERE hash = ?').bind(h).run();return json({ok:true})}const r=await db.prepare('SELECT user_id, email, name, expires FROM sessions WHERE hash = ? AND expires > ?').bind(h,now).first();if(!r)return json({error:'Session expired.'},401);return json({user:{id:r.user_id,email:r.email,name:r.name},expiresAt:r.expires})}
return json({error:'Not found.'},404);
}catch{return json({error:'The account service could not complete this request. Try again.'},500)}}};
