---
module: "bootloader"
title: "Boot Loader"
modulePackage: "grub2"
efiBootloaderInstall: true
efiBootloaderId: "KorrinOS"
grubTimeout: 5
grubTheme: "korrinos"
grubModules: ["part_gpt", "part_msdos", "btrfs", "ext2", "fat", "ntfs", "lvm", "luks"]
