---
module: "finished"
title: "Installation Complete"
text: |
  <h1>KorrinOS has been installed successfully!</h1>
  <p>Please restart your computer to start using KorrinOS.</p>
  <p>Don't forget to remove the installation media.</p>
restartNowLabel: "Restart Now"
restartLaterLabel: "Restart Later"
