---
module: "packages"
packageManager: "apt"
operations:
  - install:
      - "korrinos-desktop"
      - "korrinos-system"
      - "korrinos-apps"
      - "korrinos-security"
  - remove:
      - "ubiquity"
      - "casper"
      - "discover"
  updateDatabase: true
  updateSystem: true
