---
module: "packages"
packageManager: "apt"
operations:
  - install:
      - "tinkeros-desktop"
      - "tinkeros-system"
      - "tinkeros-apps"
      - "tinkeros-security"
  - remove:
      - "ubiquity"
      - "casper"
      - "discover"
  updateDatabase: true
  updateSystem: true
