---
module: "services"
title: "System Services"
enabledServices:
  - "NetworkManager"
  - "systemd-timesyncd"
  - "ufw"
  - "lightdm"
  - "systemd-timesyncd"
disabledServices:
  - "cups"
  - "avahi-daemon"
  - "modemmanager"
