---
module: "users"
title: "User Account"
defaultGroups: ["wheel", "network", "video", "audio", "storage", "power", "lp", "scanner"]
autologinGroup: "autologin"
sudoersGroup: "wheel"
setRootPassword: false
availableShells: ["/bin/bash", "/bin/zsh", "/bin/fish"]
defaultShell: "/bin/bash"
avatarPath: ":/images/avatars"
defaultAvatar: "user.png"
