---
module: "welcome"
title: "Welcome to KorrinOS"
text: |
  <h1>Welcome to KorrinOS Installer</h1>
  <p>KorrinOS is a Linux-based operating system designed for everyone.</p>
  <p>It combines the power of Linux with the simplicity you expect.</p>
  <p><b>Your Computer. Your Rules.</b></p>
nextLabel: "Next"
