# SPDX-License-Identifier: GPL-2.0
#
# Makefile for TinkerOS core kernel features
#

obj-$(CONFIG_TINKER_CORE)		+= tinker.o
obj-$(CONFIG_TINKER_THERMAL_SCHED)	+= thermal_sched.o
obj-$(CONFIG_TINKER_GAMEMODE)		+= gamemode.o
obj-$(CONFIG_TINKER_ENERGY_SCHED)	+= energy_sched.o
obj-$(CONFIG_TINKER_BATTERY_LIFE)	+= battery_life.o
obj-$(CONFIG_TINKER_OLED_WEAR)		+= oled_wear.o
obj-$(CONFIG_TINKER_CACHE_TIERING)	+= cache_tiering.o
obj-$(CONFIG_TINKER_COIL_WHINE)		+= coil_whine.o
obj-$(CONFIG_TINKER_SHREDDER)		+= data_shredder.o
obj-$(CONFIG_TINKER_DUST_DISLODGER)	+= dust_dislodger.o
obj-$(CONFIG_TINKER_FPGA_SCALER)	+= fpga_scaler.o
obj-$(CONFIG_TINKER_ZERO_LATENCY)	+= zero_latency_input.o
obj-$(CONFIG_TINKER_CXL_MEMORY)		+= cxl_memory.o
obj-$(CONFIG_TINKER_DVFS_SHAVER)	+= dvfs_shaver.o
obj-$(CONFIG_TINKER_HW_DNA)		+= hardware_dna.o
obj-$(CONFIG_TINKER_RAY_AUDIO)		+= ray_traced_audio.o
obj-$(CONFIG_TINKER_NEURAL_AUDIO)	+= neural_audio.o
obj-$(CONFIG_TINKER_PREWARM)		+= predictive_prewarm.o
obj-$(CONFIG_TINKER_POWER_GRID)		+= smart_power_grid.o
obj-$(CONFIG_TINKER_ADAPTIVE_DISPLAY)	+= adaptive_display.o
obj-$(CONFIG_TINKER_UNIFIED_MEM)	+= unified_memory.o
obj-$(CONFIG_TINKER_HW_TUNING)		+= hardware_tuning.o
obj-$(CONFIG_TINKER_NEURAL_SUPERRES)	+= neural_super_res.o
obj-$(CONFIG_TINKER_PREDICT_RENDER)	+= predictive_render.o
obj-$(CONFIG_TINKER_REMOTE_HW)		+= remote_hardware_api.o
obj-$(CONFIG_TINKER_SDGPU)		+= sdgpu.o
obj-$(CONFIG_TINKER_FINANCE_AUDIT)	+= finance_audit.o
