[Plymouth Theme]
Name=TinkerOS
Description=TinkerOS branded boot splash
ModuleName=script

[script]
ImageDir=/usr/share/plymouth/themes/tinkerosplymouth
ScriptFile=/usr/share/plymouth/themes/tinkerosplymouth/tinkerosplymouth.script