[Plymouth Theme]
Name=KorrinOS
Description=KorrinOS branded boot splash
ModuleName=script

[script]
ImageDir=/usr/share/plymouth/themes/korrinosplymouth
ScriptFile=/usr/share/plymouth/themes/korrinosplymouth/korrinosplymouth.script