#!/usr/bin/env bash
# codegen.sh — code generation, debugging, translation between languages, documentation

# Generate boilerplate code in various languages
ai_code_generate() {
  local lang="$1" name="${2:-main}"
  case "$lang" in
    python|py)
      cat <<EOF
#!/usr/bin/env python3
\"\"\"
$name — generated by VOKK v4
\"\"\"

import sys
import os

def main():
    \"\"\"Main entry point.\"\"\"
    print(f"Hello from {__file__}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
EOF
      ;;
    javascript|js)
      cat <<EOF
/**
 * $name — generated by VOKK v4
 */

function main() {
    console.log(\`Hello from \${__filename}\`);
}

main();
EOF
      ;;
    bash|sh)
      cat <<EOF
#!/usr/bin/env bash
# $name — generated by VOKK v4
set -euo pipefail

main() {
    echo "Hello from \$0"
}

main "\$@"
EOF
      ;;
    c)
      cat <<EOF
/* $name — generated by VOKK v4 */
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[]) {
    printf("Hello from %s\\n", argv[0]);
    return 0;
}
EOF
      ;;
    rust|rs)
      cat <<EOF
//! $name — generated by VOKK v4

fn main() {
    println!("Hello from {}", env!("CARGO_PKG_NAME"));
}
EOF
      ;;
    go|golang)
      cat <<EOF
package main

import "fmt"

func main() {
    fmt.Println("Hello from main.go")
}
EOF
      ;;
    java)
      cat <<EOF
public class $name {
    public static void main(String[] args) {
        System.out.println("Hello from $name");
    }
}
EOF
      ;;
    *)
      echo "Unsupported language: $lang"
      echo "Supported: python, javascript, bash, c, rust, go, java"
      ;;
  esac
}

# Debug: analyze error messages and suggest fixes
ai_code_debug() {
  local error_text="$1"
  echo "$error_text" | python3 -c "
import sys, re
error = sys.stdin.read().strip()
suggestions = []

# Python errors
if 'SyntaxError' in error:
    line = re.search(r'line (\d+)', error)
    suggestions.append(f'Check syntax around line {line.group(1) if line else \"unknown\"}')
    suggestions.append('Look for missing colons, brackets, or quotes')
elif 'NameError' in error:
    name = re.search(r\"name '(\w+)'\", error)
    suggestions.append(f'Variable/function \"{name.group(1) if name else \"?\"}\" is not defined')
    suggestions.append('Check for typos or missing imports')
elif 'ImportError' in error or 'ModuleNotFoundError' in error:
    mod = re.search(r\"No module named '(\w+)'\", error)
    suggestions.append(f'Install: pip install {mod.group(1) if mod else \"<module>\"}')
elif 'TypeError' in error:
    suggestions.append('Check argument types — wrong type passed to function')
    suggestions.append('Verify function signature matches your call')
elif 'IndexError' in error:
    suggestions.append('Array/list index out of range — check bounds')
elif 'KeyError' in error:
    suggestions.append('Dictionary key not found — check spelling or use .get()')
elif 'FileNotFoundError' in error:
    suggestions.append('File path does not exist — verify the path')
elif 'PermissionError' in error:
    suggestions.append('Insufficient permissions — try sudo or check file perms')
elif 'ConnectionRefused' in error:
    suggestions.append('Server not running or wrong port — verify the service')
elif 'timeout' in error.lower():
    suggestions.append('Operation timed out — check network or increase timeout')

# General
if not suggestions:
    suggestions.append('Review the stack trace for the failing line')
    suggestions.append('Check variable values at that point')
    suggestions.append('Search for the exact error message online')

print('## Debug Analysis')
print(f'Error: {error[:200]}')
print()
print('### Suggestions:')
for i, s in enumerate(suggestions, 1):
    print(f'{i}. {s}')
" 2>/dev/null || echo "Could not analyze error. Please share the full error message."
}

# Convert code between languages (basic patterns)
ai_code_translate() {
  local from_lang="$1" to_lang="$2" code="$3"
  echo "/* Translation from $from_lang to $to_lang — conceptual mapping */"
  echo "/* Original ($from_lang): */"
  echo "$code" | head -20
  echo ""
  echo "/* Note: Direct translation may need manual adjustment */"
  echo "/* Key differences to check: */"
  echo "/* - Type systems */"
  echo "/* - Error handling patterns */"
  echo "/* - Library equivalents */"
  echo "/* - Memory management */"
}

# Generate documentation for code
ai_code_document() {
  local code="$1" lang="${2:-auto}"
  echo "$code" | python3 -c "
import sys, re
code = sys.stdin.read()
lines = code.strip().split('\n')

print('## Code Documentation')
print()

# Detect functions
for i, line in enumerate(lines):
    # Python functions
    m = re.match(r'def\s+(\w+)\s*\((.*?)\):', line)
    if m:
        name, args = m.group(1), m.group(2)
        print(f'### \`{name}({args})\`')
        # Look for docstring
        if i+1 < len(lines) and '\"\"\"' in lines[i+1]:
            doc = lines[i+1].replace('\"\"\"', '').strip()
            print(f'Description: {doc}')
        print(f'Line: {i+1}')
        print()
        continue
    # JS/C functions
    m = re.match(r'(?:function\s+)?(\w+)\s*\((.*?)\)\s*{', line)
    if m and not line.strip().startswith('//'):
        name, args = m.group(1), m.group(2)
        if name not in ('if', 'for', 'while', 'switch', 'catch'):
            print(f'### \`{name}({args})\`')
            print(f'Line: {i+1}')
            print()

# Count metrics
funcs = len(re.findall(r'def\s+\w+|function\s+\w+', code))
classes = len(re.findall(r'class\s+\w+', code))
comments = len(re.findall(r'^\s*(#|//|/\*)', code, re.M))
print(f'---')
print(f'Functions: {funcs} | Classes: {classes} | Comments: {comments} | Lines: {len(lines)}')
" 2>/dev/null || echo "Unable to generate documentation."
}

# Build regex from description
ai_code_regex() {
  local description="${1,,}"
  case "$description" in
    *email*) echo '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}' ;;
    *url*|*link*|*http*) echo 'https?://[^\s<>\"'"'"']+' ;;
    *phone*|*number*) echo '\+?[0-9]{1,4}[-.\s]?[0-9]{1,4}[-.\s]?[0-9]{1,9}' ;;
    *ip*|*address*) echo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' ;;
    *date*) echo '[0-9]{4}[-/][0-9]{2}[-/][0-9]{2}' ;;
    *time*) echo '[0-9]{2}:[0-9]{2}(:[0-9]{2})?' ;;
    *word*) echo '[a-zA-Z]+' ;;
    *number*|*digit*) echo '[0-9]+(\.[0-9]+)?' ;;
    *hex*|*color*) echo '#[0-9a-fA-F]{6}' ;;
    *ipv6*) echo '([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}' ;;
    *) echo '.*' ;; # fallback: match anything
  esac
}
