---
installerName: "KorrinOS Installer"
windowTitle: "Welcome to KorrinOS Installer"
windowIcon: "korrinos"
progress: true
showSummary: true
QuitOnClose: true
QuitOnCloseConfirmation: true
DisableKeyboardLayout: false
QuitConfirmation: true
FirstRunCommand: ""
LastRunCommand: ""

windowSize: [800, 600]
sidebarMode: true
branding: "korrinos"
style: "Fusion"
