---
installerName: "TinkerOS Installer"
windowTitle: "Welcome to TinkerOS Installer"
windowIcon: "tinkeros"
progress: true
showSummary: true
QuitOnClose: true
QuitOnCloseConfirmation: true
DisableKeyboardLayout: false
QuitConfirmation: true
FirstRunCommand: ""
LastRunCommand: ""

windowSize: [800, 600]
sidebarMode: true
branding: "tinkeros"
style: "Fusion"
